"""Initial migration

Revision ID: 8a03b4a91569
Revises: 
Create Date: 2026-01-27 16:58:58.663854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a03b4a91569'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('congestion_index', sa.Float(), nullable=False),
    sa.Column('time_of_day', sa.String(), nullable=False),
    sa.Column('weather', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('festival', sa.String(), nullable=True),
    sa.Column('actual_travel_time_min', sa.Float(), nullable=False),
    sa.Column('road_type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_records_id'), 'travel_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_records_id'), table_name='travel_records')
    op.drop_table('travel_records')
    # ### end Alembic commands ###
